accountapp/urls.py
from django.urls import path, reverse_lazy
from .views import hello_world
from .views import AccountCreateView, AccountDetailView, AccountUpdateView,AccountDeleteView
from django.contrib.auth.views import LoginView, LogoutView


app_name = "accountapp"
urlpatterns = [
    path('hello_world/', hello_world, name = "hello_world"),
    
    path('login/', LoginView.as_view(template_name = "accountapp/login.html"), name = "login"),
    path('logout/', LogoutView.as_view(), name = "logout"),
    
    path('detail/<int:pk>', AccountDetailView.as_view(), name = "detail"),
    path('update/<int:pk>', AccountUpdateView.as_view(),name = "update"),
    #-- 몇 번 유저한테 접근할지 primary key 필요
    
    path('create/', AccountCreateView.as_view(), name = "create"),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name = "delete"),
    
]

fullstackproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accountapp.urls")),
    path('profiles/', include("profileapp.urls")),      
    path('articles/', include("articleapp.urls")),      
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path, reverse_lazy
from profileapp.views import ProfileCreateView,ProfileUpdateView

app_name = "profileapp"
urlpatterns = [    
    path('create/', ProfileCreateView.as_view(), name="create"),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name="update"),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=25, null=False)

accountapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accountapp.decorators import account_ownership_required
from accountapp.models import HelloWorld

has_ownership = [login_required,
                 account_ownership_required]

# Create your views here.
@login_required
def hello_world(request):
    if request.method == "POST":
        temp = request.POST.get("account_input")
        newModel = HelloWorld()
        newModel.text = temp
        newModel.save()
        HelloWorldList = HelloWorld.objects.all()
        return HttpResponseRedirect(reverse("accountapp:hello_world"))
    else:
        HelloWorldList = HelloWorld.objects.all()
        return render(request, "accountapp/hello_world.html", context={"HelloWorldList" : HelloWorldList})

class AccountCreateView(CreateView): #-- 장고에서 제공해주는 CreateView 상송
    model = User #-- 장고에서 제공해주는 user에대한 model import
    form_class = UserCreationForm  #-- 회원가입을 위한 장고에서 제공해주는 form
    success_url = reverse_lazy("accountapp:hello_world") #-- 성공한 경우 되돌아갈 페이지 지정 함수형 view -> reverse
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = "accountapp/detail.html"

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')       
class AccountUpdateView(PasswordChangeView):
    model = User
    template_name = "accountapp/update.html"
    success_url = reverse_lazy("accountapp:hello_world") #-- 성공한 경우 되돌아갈 페이지 지정 함수형 view -> reverse
    
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')       
class AccountDeleteView(DeleteView):
    model = User
    template_name = "accountapp/delete.html"
    context_object_name = 'target_user'
    success_url = reverse_lazy("accountapp:login") #-- 성공한 경우 되돌아갈 페이지 지정 함수형 view -> reverse
    

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%block content%}

<div style="text-align:center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
                <h4>회원가입</h4>
                
        </div>
        <form action = "{%url 'accountapp:create'%}", method="post">
                {%csrf_token%}
                <!-- {{ form }} -->
                {%bootstrap_form form%}
                <input type="submit", class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
</div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%block content%}

<div style="text-align:center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
                <h4>회원탈퇴</h4>
                
        </div>
        <form action = "{%url 'accountapp:delete' pk=target_user.pk%}", method="post">
                {%csrf_token%}
                <!-- {{ form }} -->
                {%bootstrap_form form%}
                <input type="submit", class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%block content%}

<div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <p>
            {{ target_user.date_joined}}
        </p>
        {%if target_user == user%}
        {%if target_user.profile%}
            <img src="{{ target_user.profile.image.url}}" alt="" style="height: 10rem; width: 10rem; border-radius:10rem; margin-bottom:2rem">
            <h2 style="font-family:'나눔손글씨 칼국수'">
                {{ target_user.profile.nickname }}
            </h2>
            
            <a href ="{%url 'profileapp:update' pk=target_user.profile.pk%}">
                <h3>
                프로필 변경
                </h3>
            </a>
            
        {%else%}
        
        <a href = "{% url 'profileapp:create'%}">
            <h2 style="font-family:'나눔손글씨 칼국수'">
                프로필 생성
            </h2>
        </a>
        {%endif%}
        {%endif%}

        {% if target_user == user %}
        <a href = "{% url 'accountapp:update' pk=user.pk %}">
            <p>
                비밀번호 변경
            </p>
        </a>
        <a href = "{% url 'accountapp:delete' pk=target_user.pk %}">
            <p>
                회원탈퇴
            </p>
        </a>
        {% endif %}
        
    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{%block content%}

<div style="height: 20rem; background-color:darkgreen; border-radius: 1rem; margin: 2rem">
        <h1 style="font-family: 'Indie Flower', cursive; ">
                HELLO WORLD TEST
        </h1>

        <form action="/account/hello_world/", method="post">
                {% csrf_token %}
                
                <!-- 텍스트입력 창  생성 -->
                <div>
                        <input type = "text" name = "account_input">
                </div>

                <!-- POST 요청 버튼 생성 -->
                <div>
                        <input type = "submit" class = "btn btn-primary" value="POST">
                </div>
        </form>

        {%if HelloWorldList %}
        {% for Helloworld in HelloWorldList%}
        <h4>
                 {{Helloworld.text}}
        </h4>
        {% endfor %}
        {% endif %}
        
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%block content%}


<div style="text-align:center; max-width: 500px; margin: 4rem auto">
    <div>
        <h4>Login</h4>
    </div>
    <div>
        <form action = "", method="post">
                {%csrf_token%}
                <!-- {{ form }} -->
                {%bootstrap_form form%}

                <input type="submit", class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
</div>

</div>


{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%block content%}

<div style="text-align:center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
                <h4>비밀번호 변경</h4>
                
        </div>
        <form action = "{%url 'accountapp:update' pk=user.pk %}", method="post">
                {%csrf_token%}
                <!-- {{ form }} -->
                {%bootstrap_form form%}
                <input type="submit", class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
</div>

{% endblock %}