accountapp/urls.py
from django.urls import path, reverse_lazy
from .views import hello_world
from .views import AccountCreateView, AccountDetailView, AccountUpdateView,AccountDeleteView
from django.contrib.auth.views import LoginView, LogoutView


app_name = "accountapp"
urlpatterns = [
    path('hello_world/', hello_world, name = "hello_world"),
    
    path('login/', LoginView.as_view(template_name = "accountapp/login.html"), name = "login"),
    path('logout/', LogoutView.as_view(), name = "logout"),
    
    path('detail/<int:pk>', AccountDetailView.as_view(), name = "detail"),
    path('update/<int:pk>', AccountUpdateView.as_view(),name = "update"),
    #-- 몇 번 유저한테 접근할지 primary key 필요
    
    path('create/', AccountCreateView.as_view(), name = "create"),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name = "delete"),
    
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from articleapp.views import ArticleCreateView,ArticleDetailView,ArticleUpdateView,ArticleDeleteView,ArticleListView

app_name = "articleapp"
urlpatterns = [
    path('list/', ArticleListView.as_view(), name = "list"),
    path('create/', ArticleCreateView.as_view(), name = "create"),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name = "detail"),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name = "update"),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name = "delete"),
]

fullstackproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accountapp.urls")),
    path('profiles/', include("profileapp.urls")),      
    path('articles/', include("articleapp.urls")),      
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{%include  'head.html'%}

<body style="font-family: '나눔손글씨 진주 박경아체' ;">
   
    {%include  'header.html'%}
    <hr>
    {%block content%}
    {%endblock%}
    <hr>
    {%include  'footer.html'%}
    
</body>
</html>

templates/footer.html
<div class="full_stack_project_footer">
    <div class="full_stack_project_footer_button">
        <span>공지사항</span> |
        <span>서비스소개</span> |
        <span>제휴문의</span>

    </div>
    <div style="margin-top :1rem">
        <h6 class="full_stack_project_logo">Full Stack Project</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Full Stack Project With Django</title>

    <!-- 부트스트랩  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">

    <!-- 구글 폰트  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gowun+Batang&family=Indie+Flower&family=Maven+Pro&family=Nanum+Pen+Script&family=Noto+Sans+KR:wght@300;700&family=Unna&display=swap" rel="stylesheet">

    <!--  CSS Link  -->
    <link rel = "stylesheet" type = "text/css" href="{% static 'base.css' %}">


    <style>
        @font-face {
            font-family: '나눔손글씨 진주 박경아체';
            src: local('나눔손글씨 진주 박경아체'),
            url("{%static 'fonts/나눔손글씨 진주 박경아체.ttf'%}") format("opentype");
        }

        @font-face {
            font-family: '나눔손글씨 칼국수';
            src: local('나눔손글씨 칼국수'),
            url("{%static 'fonts/나눔손글씨 칼국수.ttf'%}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="full_stack_project_header_navn">
    <div>
        <h1 class="full_stack_project_logo">Full Stack Project</h1>
    </div>
    <div>
        <a href="{%url 'articleapp:list'%}">
            <span> Article </span>
        </a>
        <span> nav2 </span>
        <span> nav3 </span>
        {%if not user.is_authenticated%}
        <a href="{%url 'accountapp:login'%}?next={{request.path}}">
            <span> 로그인 </span>
        </a>
        <a href="{%url 'accountapp:create'%}?next={{request.path}}">
            <span> 회원가입 </span>
        </a>
        {% else %}
        <a href="{%url 'accountapp:detail' pk=user.pk%}">
            <span> 마이페이지 </span>
        </a>
        <a href="{%url 'accountapp:logout'%}?next={{request.path}}">
            <span> 로그아웃 </span>
        </a>
        {% endif %}
        
    </div>
</div>